version: '3.7'

services:

  chanter:
    restart: always
    build: .
    command: nodemon -L --watch views chanter.js
    environment:
      NODE_ENV: production
      DB_CONNECTION: http://localhost/phpmyadmin/db_structure.php?server=2&db=chanter-dev&token=664921db6bdfc23fa65126bfebc1ff6c
      VIRTUAL_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    links:
    - mariadb
    depends_on:
    - mariadb


  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3307
      VIRTUAL_HOST: PHPMYADMINDOMAINS.grp3.p645.hevs.ch
      LETSENCRYPT_HOST: PHPMYADMINDOMAINS.grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    volumes:
    - /sessions
    depends_on:
    - mariadb


  mariadb:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      mariadb
      MYSQL_USER:          dev
      MYSQL_PASSWORD:      unlucky
      DATABASE_PORT_NUMBER: 3307
    volumes:
    - /var/lib/mysql/data


networks:
  default:
    external:
      name: webproxy
