version: '3.3'

services:

  chanter:
    restart: always
    build: .
    command: nodemon -L --watch views chanter.js
    ports:
    - "3000:3000"
    environment:
    - NODE_ENV=development
    links:
    - mariadb
    depends_on:
    - mariadb

  mariadb:
    restart: always
    image: mariadb
<<<<<<< HEAD
    ports:
    - "3307:3306"
    volumes:
    - /var/lib/mysql/data
    environment:
    - MYSQL_ROOT_PASSWORD=root
=======
    environment:
    - MYSQL_ROOT_PASSWORD=root


networks:
  default:
    external:
      name: webproxy
>>>>>>> origin/devBranch
