version: '3.7'

services:

  chanter:
    restart: always
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    depends_on:
      - mariadb

  mariadb:
    restart: always
    image: mariadb
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: dev-branch
     MYSQL_USER: dev
     MYSQL_PASSWORD: unlucky

networks:
  default:
    external:
      name: webproxy
