version: '3.7'

services:

  chanter:
    container_name: chanter
    restart: always
    build: .
    ports:
    - "3000:3000"
    environment:
    - NODE_ENV=development
    links:
    - mariadb

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb
    ports:
    - "3306:3307"
    volumes:
    - /var/lib/mysql/data
    environment:
    - MYSQL_ROOT_PASSWORD=root
