version: '3.7'

services:

  chanter:
    restart: always
    build: .
    command: nodemon -L --watch views chanter.js
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    links:
    - mariadb
    depends_on:
    - mariadb

  mariadb:
    restart: always
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    restart: always
    environment:
      PMA_PORT: 3306
      VIRTUAL_HOST: PHPMYADMINDOMAINS.grp3.p645.hevs.ch
      LETSENCRYPT_HOST: PHPMYADMINDOMAINS.grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    volumes:
    - /sessions
    depends_on:
    - mariadb

networks:
  default:
    external:
      name: webproxy
