services:

  chanter:
    restart: always
    build: .
    command: nodemon -L --watch views chanter.js
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${EMAIL}
    links:
    - mariadb
    depends_on:
    - mariadb

  mariadb:
    restart: always
    image: mariadb
    environment:
     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
     MYSQL_DATABASE: $DB_DATABASE
     MYSQL_USER: $DB_USER
     MYSQL_PASSWORD: $DB_PASSWORD


networks:
  default:
    external:
      name: ${NETWORK}
