version: '3.7'

services:

  chanter:
    build: .
    command: nodemon -L --watch views chanter.js
    environment:
      NODE_ENV: production
      DB_CONNECTION: mariadb://dev:unlucky@mariadb:3307/chanter-dev
      VIRTUAL_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_HOST: grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    restart: always
    depends_on:
    - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: dev
      PMA_PASSWORD: unlucky
      VIRTUAL_HOST: phpmyadmindomains.grp3.p645.hevs.ch
      LETSENCRYPT_HOST: phpmyadmindomains.grp3.p645.hevs.ch
      LETSENCRYPT_EMAIL: aurelie.glassey@students.hevs.ch
    volumes:
    - /sessions
    depends_on:
    - mariadb


  mariadb:
    image: mariadb
    restart: always
    environment:
    volumes:
      - /var/lib/mysql/data

networks:
  default:
    external:
      name: webproxy
